### 1D Array with Numpy

Imports

In [2]:
#numpy, pytorch import
import numpy as np
import torch

2D는 (batch size, dim)이며 세로를 batch, 가로를 dim이라 한다.
3D는 (batch size, width, height)이며 cube를 기준으로하면 각각 (높이, 가로, 세로)에 해당한다.

Training Data

In [2]:
#create array
t = np.array([ 0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
#numpy를 통해 array의 dim과 shape 확인 및 출력 (1개의 차원과 7개의 element)
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 1
Shape of t: (7,)


### 2D Array with Numpy

In [7]:
#2차원 array 생성
t2 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t2)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t2:', t2.ndim)
print('Shape of t2:', t2.shape)

Rank of t2: 2
Shape of t2: (4, 3)


### In Pytorch

In [10]:
# 1D Array with Pytorch
# Torch의 Float형 Tensor로 생성
tp = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(tp)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [12]:
#torch에서 array를 분석하는 다양한 함수 사용
print(tp.dim())
print(tp.shape)
print(tp.size()) #shape와 같은 결과 출력
print(tp[0], tp[1], tp[-1])
print(tp[2:5], tp[4:-1])
print(tp[:2], tp[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [14]:
# 2D Array with Pytorch
tp2 = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(tp2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
print(tp2.dim())
print(tp2.shape) #만약 차원 내 원소의 갯수가 맞지 않을 경우 출력은 어떻게 될까?
print(tp2.size()) #shape와 같은 결과 출력
print(tp2[0], tp2[1], tp2[-1])
print(tp2[2:5], tp2[4:-1])
print(tp2[:2], tp2[3:])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([1., 2., 3.]) tensor([4., 5., 6.]) tensor([10., 11., 12.])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]]) tensor([], size=(0, 3))
tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([[10., 11., 12.]])


#### Broadcasting

In [16]:
#same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print( m1 + m2 )

tensor([[5., 5.]])


In [17]:
#Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 크기가 다르지만 [3] -> [3, 3]으로 자동 변환되어 계산된다
print(m1 + m2)

tensor([[4., 5.]])


In [18]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
# m1 = [[1, 2]] -> [[1, 2], [1, 2]]
# m2 = [[3], [4]] -> [[3, 3], [4, 4]]
# 로 자동 변환되어 계산된다
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


#### Multiplication vs Matrix Multiplication

In [22]:
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2)) #

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape) #broadcasting을 통해 2x1 matrix가 2x2 matrix로 변형된다.
#[[1], [2]] -> [[1, 2], [1, 2]]
print(m1 + m2)
print(m1.mul(m2))

-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[2., 3.],
        [5., 6.]])
tensor([[1., 2.],
        [6., 8.]])


#### Mean

In [23]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [28]:
#Can't use mean() on integer
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [26]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [27]:
print(t.mean()) # 전체 dim elements의 mean
# 해당하는 dim을 제외하고 mean을 수행
print(t.mean(dim=0)) # 2x2 -> 1x2
print(t.mean(dim=1)) # 2x2 -> 2x1
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


#### Sum

In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### Max and Argmax

In [32]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [33]:
print(t.max())

tensor(4.)


In [36]:
print(t.max(dim=0)) #max와 Argmax값을 같이 return한다.
# Argmax는 함수 f(x)를 최대로 만드는 x값을 의미한다. 따라서 여기에선
# 해당 배열의 index를 return하게된다.
print('Max: ',t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [37]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### VIew

In [5]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [32]:
# -1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미이고
# 3은 두번째 차원의 길이는 3을 가지도록 하라는 의미
# 다시 말해 현재 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로 변경하라는 의미입니다.
# 결과적으로 (4, 3)의 크기를 가지는 텐서를 얻었습니다.
a = ft.view([-1, 3])
print(a)
print(a.shape)

print('내부적으로 크기 변환은 다음과 같이 이루어졌습니다. (2, 2, 3) -> (2 × 2, 3) -> (4, 3)')

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
내부적으로 크기 변환은 다음과 같이 이루어졌습니다. (2, 2, 3) -> (2 × 2, 3) -> (4, 3)


In [30]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
